#!/bin/bash

root=$(git rev-parse --show-toplevel)

grep -n '[[:space:]]$' $root/README.md\
    $root/Cargo.toml\
    $root/CHANGELOG.md\
    $root/deny.toml\
    $root/README.md\
    $root/scripts/*\
    $root/src/*\
