name: cargo-deny

on: [push, pull_request]

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get cargo-deny
      run: cargo install --locked cargo-deny
    - name: Run cargo-deny
      run: cargo deny check
